logging:
  level: INFO
twitch:
  accessToken: accesstoken_123
  clientId: client_id_123
  clientSecret: client_secret_123
  prefix: "!"
  channels:
    - channel_a
    - channel_b
  caseInsensitive: No
  refreshToken: refreshtoken_123
webhook:
  port: 12345
obs:
  port: 12345
  password: password_123