logging:
  level: INFO
chat:
  access_token: accesstoken_123
  client_id: client_id_123
  client_secret: client_secret_123
  prefix: "!"
  channels:
    - channel_a
    - channel_b
  case_insensitive: No
  refresh_token: refreshtoken_123
  event_sub:
    callback: https://example.url/eventsub
    listen_port: 12345
    secret: event_sub_secret
webhook:
  port: 12345
obs:
  port: 12345
  password: password_123
  callbacks: No
twinkly:
  - http://192.168.0.101/xled/v1/
  - http://192.168.0.102/xled/v1/